export const applicationSummaryConfig = Object.freeze({
  title: "Interview Cheat Sheet",
  description: "Prep organized by the people you will meet",
  actions: {
    generate: "Generate cheat sheet",
    regenerate: "Regenerate cheat sheet",
    retry: "Retry cheat sheet",
    print: "Print or Save as PDF",
    printSection: "Print this section",
  },
  sections: {
    overview: "At a glance",
    thirtySecondFit: "30-second fit",
    careerRecap: "Career recap",
    gapsToPrepare: "Gaps to be ready for",
    company: "Company",
    position: "Position",
    people: "People you will meet",
    caresAbout: "What they care about",
    bestMaterial: "Your best material",
    likelyQuestions: "Likely questions",
    questionsToAsk: "Questions to ask them",
    thisStoryAnswers: "This story answers:",
    stories: "Stories",
    interviewStages: "Interview stages",
    nextStage: "Next stage",
    completedStages: "Completed stages",
    recruiterSummary: "60-second career summary",
    whyThisCompany: "Why this company",
    whyThisRole: "Why this role",
    logistics: "Logistics",
    compensation: "Compensation readiness",
    flagAnswers: "Flags to address honestly",
    firstNinetyDays: "First 90 days",
    drillDowns: "Likely drill-downs",
    scorecard: "Scorecard outcomes",
    strategy: "Strategy",
    judgment: "Judgment",
    businessImpact: "Business impact",
    howWorkedAcross: "Working across their function",
    dayToDay: "Day to day with this person",
  },
  cultureEvidenceLabel: "Based on limited public evidence",
  missingWhyThisCompany:
    "State why you want this company in the Personal Profile. This is not answered by a work story.",
});
