import { vocab } from "./vocabulary";

export const candidateProfileEditCopy = Object.freeze({
  pageTitle: `Edit ${vocab.product.singular}`,
  pageHelp: "Update the facts a resume and applications should use.",
  save: `Save ${vocab.product.singular}`,
  saved: `${vocab.product.Singular} saved.`,
  nameRequired: "Full name is required.",
  identityTitle: "Identity and contact",
  directionTitle: "Positioning and career direction",
  experienceTitle: "Experience",
  extrasTitle: "Skills, education, credentials, and awards",
  fullName: "Full name",
  headline: "Headline",
  cityState: "City and state",
  phone: "Phone",
  email: "Email",
  linkedinUrl: "LinkedIn URL",
  linkedinHint: "Optional. Included on the resume only when you add it.",
  personalWebsite: "Personal website",
  personalWebsiteHint: "Optional. A personal site, portfolio, or GitHub URL.",
  positioning: "Positioning statement",
  targetTitles: "Target titles",
  functions: "Career functions",
  seniority: "Seniority",
  goals: "Career goals",
  onePerLine: "One per line.",
  employer: "Employer",
  title: "Title",
  startDate: "Start date",
  endDate: "End date",
  location: "Location",
  summary: "Role summary",
  achievements: "Achievements",
  dateHint:
    "Write the date as you want it shown, such as 2021-03, 2021, or Present.",
  addRole: "Add role",
  removeRole: "Remove role",
  moveRoleUp: "Move role up",
  moveRoleDown: "Move role down",
  addAchievement: "Add achievement",
  removeAchievement: "Remove achievement",
  moveAchievementUp: "Move achievement up",
  moveAchievementDown: "Move achievement down",
  skills: "Skills",
  education: "Education",
  credentials: "Credentials",
  awards: "Awards",
  problemsSolved: "Problems solved for employers",
  differentiators: "Differentiators",
  domainVocabulary: "Domain vocabulary",
  emptyBlurb: "No headline yet.",
  seekerEditSource: "Edited by you",
  seekerBackgroundSource: "Told by you",
});
